### ISSUE TITLE
Move sliding layer with finger when using offsetDistance

### ISSUE THREAD

**Issue by chetanmekha** [wunderlist/android-sliding-layer-lib#68]
Hello,
This library is very useful and working perfectly in my application.
But I want to allow user to swipe from left to right and then move the sliding layer as per the movement of  finger. e.g. android Gmail application. 
This is working when user try to close already opened layer by touching on layer and move the finger(In this case sliding layer moves along with finger which exactly i want while opening the layer).

Maybe this is already implemented in library,in that case..am i missing something?

**Comment by JlUgia** [comment]
Hi chetanmehka! (not easy to spell :)

Valid point. This is in fact something we wanted to stay away from doing. We have the feeling that it is not a great hint in terms of UX to pull something from empty space like the SlidingDrawer does. 

But you can do something about it -and hopefully it is also nicer to users-. There's a property called `offsetDistance` - see README-. If you specify some value greater than 0, the layer will show a bit of it from the side where you stick it to, so that users see there's something there they cal pull from.
If you do not want to show part of the entire layer you can also show a small handle at the edge (the way Google Maps used to do).

Hope it's helpful.

**Comment by chetanmekha** [comment]
Hi again,

I am able achieve the swiping  using the offset.
Actually using transparent layout at end of sliding layout(width=10dp) done the trick!
Thanks for your help.

You can close this.

**Comment by JlUgia** [comment]
Yah, I really do not want to pollute your use case, but if I may I would recommend using some visual indication to the user that the layer is there.
Thanks for your feedback!
